steps:
  - label: ":mag: Audit shared and desktop dependencies"
    command: "cd src/shared && yarn audit && cd ../desktop && yarn audit && cd ../.."
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-desktop-ci"

  - wait

  - label: ":eslint: Run ESLint for shared and desktop"
    command: "yarn lint:shared && yarn lint:mobile"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-desktop-ci"

  - wait

  - label: ":react: Bundle"
    command: "cd src/desktop && yarn build"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-desktop-ci"
