steps:
  - label: ":mag: Audit shared dependencies"
    command: "cd src/shared && yarn audit && cd ../.."
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-desktop-ci"

  - wait

  - label: ":mag: Audit desktop dependencies"
    command: "cd src/desktop && yarn audit && cd ../.."
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-desktop-ci"

  - wait

  - label: ":eslint: Run ESLint for desktop"
    command: "yarn lint:desktop"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-desktop-ci"

  - wait

  - label: ":eslint: Run ESLint for shared"
    command: "yarn lint:shared"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-desktop-ci"

  - wait

  - label: ":react: Bundle"
    command: "cd src/desktop && yarn build"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-desktop-ci"
