steps:
  - label: ":hammer_and_wrench: Build for all platforms"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && yarn"
      - "./bugsnag.sh && node bugsnag.js"
      - "yarn build && yarn release"
    artifact_paths:
      - "out/*"
    agents:
      queue: mac
    env:
      WIN_CSC_LINK: "./cert.p12"
