steps:
  - label: ":hammer_and_wrench: Build for all platforms"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && yarn && cd ../.."
      - "cd src/desktop && yarn build && node_modules/.bin/electron-builder -mwl"
    artifact_paths:
      - "out/*"

  - wait

# TODO: GitHub release tasks
