env:
    browser: true
    es6: true
    commonjs: true
    node: true
    mocha: true
    jest: true
parser: babel-eslint
parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
        experimentalObjectRestSpread: true
        jsx: true
        modules: true
        arrowFunctions: true
        classes: true
        spread: true
    sourceType: module
extends:
    - airbnb
    - eslint:recommended
    - plugin:react/recommended
    - prettier/react
    - prettier
plugins:
    - babel
    - react
    - jsx-a11y
settings:
    import/resolver:
        node:
            extensions:
                - .js
                - .json
                - .css
            paths:
                - ./src/desktop/src
                - ./src/shared
                - ./src/mobile/src

rules:
    no-unused-vars: ['error', { 'argsIgnorePattern': '^_' }]
    import/no-cycle: 0
    import/no-extraneous-dependencies: 0
    import/no-unresolved: 0
    jsx-a11y/alt-text: 0
    jsx-a11y/label-has-for: 0
    jsx-a11y/anchor-is-valid: 0
    jsx-a11y/no-autofocus: 0
    jsx-a11y/click-events-have-key-events: 0
    jsx-a11y/no-static-element-interactions: 0
    jsx-a11y/no-noninteractive-element-interactions: 0
    react/default-props-match-prop-types: 0
    react/destructuring-assignment: 0
    react/forbid-prop-types: 0
    react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }]
    react/no-array-index-key: 0
    react/require-default-props: 0
    react/sort-comp: [2, { 'order': ['static-variables', 'static-methods', 'lifecycle', 'everything-else', 'render'] }]
