env:
    browser: true
    es6: true
    commonjs: true
    node: true
    mocha: true
    jest: true
parser: babel-eslint
parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
        experimentalObjectRestSpread: true
        jsx: true
        modules: true
        arrowFunctions: true
        classes: true
        spread: true

    sourceType: module
extends:
    - airbnb
    - eslint:recommended
    - plugin:react/recommended
    - prettier/react
    - prettier
plugins:
    - babel
    - react
    - jsx-a11y
settings:
    import/resolver:
        node:
            extensions:
                - .js
                - .json
                - .css
            paths:
                - ./src/desktop/src
                - ./src/shared

rules:
    arrow-parens: [2, "always"]
    block-scoped-var: 2
    brace-style: [2, 1tbs, { "allowSingleLine": true }]
    camelcase: 2
    curly: [2, "all"]
    dot-location: [1, "property"]
    dot-notation: 2
    eol-last: 2
    eqeqeq: 2
    key-spacing: 2
    keyword-spacing: 2
    linebreak-style: [2, "unix"]
    no-alert: 2
    no-console: 1
    no-else-return: 1
    no-empty: [2, { "allowEmptyCatch": true }]
    no-eq-null: 2
    no-eval: 2
    no-extend-native: 2
    no-floating-decimal: 2
    no-implicit-coercion: [2, { "allow": ["!!"] }]
    no-implied-eval: 2
    no-lone-blocks: 2
    no-loop-func: 2
    no-multi-spaces: 2
    no-multi-str: 2
    no-native-reassign: 2
    no-new: 2
    no-new-func: 2
    no-new-wrappers: 2
    no-octal-escape: 2
    no-return-assign: 2
    no-script-url: 2
    no-self-compare: 2
    no-sequences: 2
    no-throw-literal: 2
    no-unmodified-loop-condition: 2
    no-unused-expressions: [2, { "allowShortCircuit": true, "allowTernary": true }]
    no-useless-call: 2
    no-useless-concat: 2
    no-var: 2
    no-void: 2
    one-var: 2
    prefer-arrow-callback: 2
    prefer-const: 2
    quotes: [2, "single"]
    semi: 2
    yoda: 2
    import/extensions: 0
    import/no-extraneous-dependencies: 0
    import/prefer-default-export: 0
    space-in-parens: [2, "never"]
    # babel/no-invalid-this: 2
    jsx-a11y/alt-text: 0
    jsx-a11y/label-has-for: 0
    jsx-a11y/anchor-is-valid: 0
    jsx-a11y/no-autofocus: 0
    jsx-a11y/click-events-have-key-events: 0
    jsx-a11y/no-static-element-interactions: 0
    jsx-a11y/no-noninteractive-element-interactions: 0
    react/default-props-match-prop-types: 0
    react/forbid-prop-types: 0
    react/jsx-equals-spacing: 2
    react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
    react/jsx-first-prop-new-line: [1, "multiline"]
    react/jsx-indent: [2, 4]
    react/jsx-wrap-multilines:
        - 2
        -
            declaration: parens-new-line
            assignment: parens-new-line
            return: parens-new-line
            arrow: parens-new-line
            prop: ignore
    react/no-array-index-key: 0
    react/prefer-stateless-function: [1, {"ignorePureComponents": true}]
    react/require-default-props: 0
