files:
  - source: /src/shared/locales/en/translation.json
    translation: /src/shared/locales/%two_letters_code%/translation.json
    languages_mapping:
      two_letters_code:
        zh-CN: zh-CN
        zh-TW: zh-TW
        es-ES: es-ES
        pt-PT: pt-PT
        sv-SE: sv-SE
        pt-BR: pt-BR
        es-419: es-LA
  - source: /src/mobile/ios/localizations/en.xliff
    translation: /src/mobile/ios/localizations/%osx_locale%.xliff
