# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 5s",
#   "iPhone 7",
#   "iPhone X"
 ])

languages([
   "en-UK",
   "ar_SA",
   "da_DK",
   "de-DE",
   "el_GR",
   "es_ES",
   "es_MX",
   "fi_FI",
   "fr_FR",
   "he_IL",
   "hi_IN",
   "id_ID",
   "it-IT",
   "ja_JP",
   "ko_KR",
   "lv_LV",
   "nl_NL",
   "nb_NO",
   "pl_PL",
   "pt_PT",
   "pt_BR",
   "ro_RO",
   "ru_RU",
   "sl_SI",
   "sv_SE",
   "tr_TR",
   "ur_PK",
   "zh_Hans_CN",
   "zh_Hant_TW"
   
 ])

# The name of the scheme which contains the UI Tests
 scheme "iotaWalletUITests"

# Where should the resulting screenshots be stored?
 output_directory "./screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
 clear_previous_screenshots true

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])
  
  stop_after_first_error true
  reinstall_app true
  localize_simulator true
  erase_simulator true

# For more information about all available options run
# fastlane action snapshot
