# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iotaWallet' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # Pods for iotaWallet
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'IotaKit'
    
    target 'iotaWalletTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

target 'iotaWallet-tvOS' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for iotaWallet-tvOS
    
    target 'iotaWallet-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
