# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iotaWallet' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
pod 'CatCrypto', :git => 'https://github.com/rajivshah3/CatCrypto.git', :branch => 'raw-hash'

    target 'iotaWalletTests' do
        inherit! :search_paths
        # Pods for testing
    end

end

target 'iotaWallet-tvOS' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for iotaWallet-tvOS

    target 'iotaWallet-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
    end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "IotaKit"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
                config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 'fast'
            end
        end
    end
end
