# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iotaWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iotaWallet
pod 'Fabric', '~> 1.7.3'
pod 'Crashlytics', '~>  3.10'
pod 'UIDevice-PasscodeStatus', '~> 0.0.2'

  target 'iotaWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iotaWallet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iotaWallet-tvOS

  target 'iotaWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
