steps:
  - label: ":pipeline: Run Trinity Mobile (PRs) pipeline"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/mobile && yarn && cd ../.."
      - "cd src/shared && yarn audit && cd ../mobile && yarn audit && cd ../.."
      - "yarn lint:shared && yarn lint:mobile"
      - "cd src/mobile && yarn test && cd ../.."
      - "cd src/mobile && react-native bundle --entry-file index.android.js --platform android --bundle-output android/main.jsbundle --dev true"
    agents:
      queue: dev
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-mobile-ci"
        always-pull: true
