steps:
  - label: ":mag: Audit shared dependencies"
    command: "cd src/shared && yarn audit && cd ../.."
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-mobile-ci"

  - wait

  - label: ":mag: Audit mobile dependencies"
    command: "cd src/mobile && yarn audit && cd ../.."
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-mobile-ci"

  - wait

  - label: ":eslint: Run ESLint for mobile"
    command: "yarn lint:mobile"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-mobile-ci"

  - wait

  - label: ":eslint: Run ESLint for shared"
    command: "yarn lint:shared"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-mobile-ci"

  - wait

  - label: ":jest: Run mobile tests"
    command: "cd src/mobile && yarn test"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-mobile-ci"

  - wait

  - label: ":react: Bundle"
    command: "cd src/mobile && react-native bundle --entry-file index.android.js --platform android --bundle-output android/main.jsbundle --dev true"
    plugins:
      docker#v1.4.0:
        image: "rajivshah/trinity-mobile-ci"
