/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iota_mobile_GarbageCollectorInterface */

#ifndef _Included_org_iota_mobile_GarbageCollectorInterface
#define _Included_org_iota_mobile_GarbageCollectorInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iota_mobile_GarbageCollectorInterface
 * Method:    runGC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_iota_mobile_GarbageCollectorInterface_runGC
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
