export const icons = {
    iota: '💥',
    wallet: '💰',
    camera: '📷',
    eye: '👁',
    chevronDown: '🔻',
    chevronUp: '🔺',
    chevronRight: '🔜',
    chevronLeft: '🔙',
    language: '💬',
    theme: '🌈',
    node: '📡',
    info: '🗯',
    twoFA: '💊',
    password: '🔒',
    advanced: '🔬',
    mode: '🔣',
    logout: '🖐',
    currency: '💵',
    send: '📤',
    receive: '📥',
    settings: '🎛',
    history: '🕐',
    user: '👽',
    plus: '🔹',
    bookmark: '📖',
    trash: '🗑',
};
