name: Rollback Trinity Desktop Release

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-18.04
    steps:
    - name: Restore previous latest.yml files
      # Replace current latest.ymls with the ones in previous/
      run: |
        aws s3 mv s3://iotaledger-files/trinity/desktop/releases/previous/ s3://iotaledger-files/trinity/desktop/releases/ --exclude "*" --include "latest*.yml" --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
